export class User {
    title: string
    email: string
    firstName: string
    lastName: string
    dob: Date
    age: number
    nationality: string
    gender: string
    identificationNumber: string
    idExpiryDate: Date
    phoneNumber: number
    alternateNumber: number
    employmentType: string
    employerName: string
    jobTitle: string
    totalExperience: string
    propertyStreet: string
    propertysector: string
    pincode: number
    purchasePrice: number
    loanAmount: number
    downPayment: number
    loanToValue: number
    monthlyIncome: number
    maritalStatus: string
    loanObligation: number
    tenure: number
}